### ISSUE TITLE
Disable the ansi output when hook runs

### ISSUE THREAD

**Issue by NigelGreenway** [sebastianfeldmann/captainhook#8]
When running the `pre-commit` hook, I get the following output:

![image](https://user-images.githubusercontent.com/2984008/27435738-f66a028a-5754-11e7-8a83-ff2f4095bd70.png)

This makes it unreadable as you can see. My configuration is the following for this hook:

![image](https://user-images.githubusercontent.com/2984008/27435747-fa9c1e10-5754-11e7-8fbd-e1073c6a684a.png)

As you can also see, running `captainhook run pre-commit --no-ansi` works fine:

![image](https://user-images.githubusercontent.com/2984008/27435852-4594377c-5755-11e7-8543-ab112ac252af.png)

So, is this a but or do I have to specify a configuration option somewhere?

**Comment by sebastianfeldmann** [comment]
This looks like a bug, what kind of OS / terminal are you using?
So I can try to reproduce this behavior

**Comment by NigelGreenway** [comment]
Running on MacOS `10.12.4 (16E195)`. I get this in both PHPStorm's terminal and the stock terminal and both with, and without tmux.

**Comment by sebastianfeldmann** [comment]
Thanks! I will have a look at this when I get home.

**Comment by NigelGreenway** [comment]
Cheers

**Comment by sebastianfeldmann** [comment]
So I did some testing and for me it looks like this:

Terminal (OSX 10.12.5):
<img width="571" alt="terminal" src="https://user-images.githubusercontent.com/9250358/27487305-a521a650-5833-11e7-9410-5e5ac6f086b7.png">
Maybe you terminal theme is a bit off?

PHPStorm (event log) when committing via PHPStorm:
<img width="908" alt="phpstorm" src="https://user-images.githubusercontent.com/9250358/27487339-bff8459c-5833-11e7-921b-acb6790d1355.png">

And this is quite intended to look this way, I think this is the Symfony Console default coloring for exceptions.

I can reproduce your output if I use the PHPStorm terminal. And you are right that isn't as readable as it should be.

I'll look for a way to deactivate the ansi coloring via `captainhook.json` or some other way

**Comment by sebastianfeldmann** [comment]
As the JetBrains guys pointed out you can configure your terminal settings.
https://twitter.com/phpstorm/status/879335576197111809

To make this behavior configurable, the configuration file JSON "scheme" had to be changed.
I'm not quite comfortable doing this.

I changed my PHPStorm terminal color scheme and now the output is clearly readable in there as well.
Remember you have to close the PHPStorm Terminal for some of the color changes, like default text color, some of the color changes can be directly seen by hitting `Apply`

**Comment by ktomk** [comment]
Captainhook uses the composer console components. The display of the exception is done by that component which has ansi coloring enabled by default.

This is configurable not only via the Symfony Console global switch `--no-ansi` but IIRC also within the default application object. It should ship with an output decorator removing all those coloring tags as-if `--no-ansi` is given.

I'd say what the reporter is concerned about is a valid case, as this is within git-hooks ansi colors should be switched off in that context. Output is normally redirected to stderr if the hook fails anyway, that is what is configurable within Phpstorm.

It would be nice to know if when the hook is run interactively if ANSI colors should still be displayed.

Also in case if the it is run as hook if the output should be given verbatim and not with the exception formatting from Symfony console (which could qualify as expected behaviour as well when porting Git hooks to Captainhook).

Reflecting both considerations (Git hook usage / interactive usage) this should improve interoperability and make integration of Captainhook easier.

I don't have a PR for this, so far only my 2 cents for the issue.

**Comment by sebastianfeldmann** [comment]
ANSI coloring is now disabled on hook executions

Fixed in version: 2.1.0

**Comment by nntoan** [comment]
@sebastianfeldmann What if I want the ANSI back? Is there any option to turn it on/off easily in the `captainhook.json` ?

**Comment by sebastianfeldmann** [comment]
I just added https://github.com/CaptainHookPhp/captainhook/issues/54 ;)

**Comment by sebastianfeldmann** [comment]
If you use the latest version 4.4.2 you can now configure the output as explained in #54
